In [1]:
import numpy as np
from copy import deepcopy

In [2]:
U = np.array([[6,0,3,6]]).T
V = np.array([[4,2,1]]).T

Y = np.array([[5, np.nan, 7], [np.nan, 2, np.nan], [4, np.nan, np.nan], [np.nan, 3, 6]])

In [3]:
X = U@V.T
print(X)
print(Y)

X.shape

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]
[[ 5. nan  7.]
 [nan  2. nan]
 [ 4. nan nan]
 [nan  3.  6.]]


(4, 3)

In [40]:
class collaborative_filtering:
    
    def __init__(self, Y, U, V, lb=1):
        self.Y = Y
        self.U = U
        self.V = V
        self.lb = lb
    
    def calculate_loss_function(self):
        sum_squared_error = self._get_sum_squared_error(self.Y, self.U, self.V)
        regularization = self._get_gegularization(self.U, self.V, self.lb)
        return sum_squared_error, regularization
    
    @staticmethod
    def _get_sum_squared_error(Y,U,V):
        X = np.matmul(U, V.T)
        sum_squared_error = 0
        
        for i in range(X.shape[0]):
            for j in range(X.shape[1]):
                if not np.isnan(Y[i][j]):
                    sum_squared_error += 1/2*((Y[i][j] - X[i][j])**2)
                    
        return sum_squared_error
    
    @staticmethod
    def _get_gegularization(U, V, lb):
        return lb/2*(np.sum(U*U)) + lb/2*((np.sum(V*V)))
    
    
    def one_step_U(self):
        U_new = np.zeros(U.shape)
        Y = deepcopy(self.Y)
        idx_nan = np.where(np.isnan(Y), 0, 1)
        Y = np.nan_to_num(Y)
        
        for i in range(U_new.shape[0]):
            Y_i = Y[i].reshape(1, Y[i].shape[0])
            idx_nan_i = idx_nan[i].reshape(1, idx_nan[i].shape[0])
            U_new[i][0] = np.matmul(Y_i,V)/(np.sum(V*V*idx_nan_i.T) + self.lb)
        
        self.U = U_new
            
        
        

In [41]:
cost_loss = collaborative_filtering(Y, U, V)
sse, regu = cost_loss.calculate_loss_function()
print(f"sse:{sse}, regularize:{regu}")

sse:255.5, regularize:51.0


In [42]:
one_step_U = collaborative_filtering(Y, U, V)
one_step_U.one_step_U()
print(one_step_U.U)

[[1.5       ]
 [0.8       ]
 [0.94117647]
 [2.        ]]


In [ ]:
z = Y[1]
z.reshape(1,3)

In [ ]:
z.reshape(1,3)